import { Product, BlogPost, Category } from "@/types";

export const categories: Category[] = [
  { id: "streaming", name: "Streaming", icon: "📺", count: 12 },
  { id: "ai-tools", name: "AI Tools", icon: "🤖", count: 18 },
  { id: "productivity", name: "Productivity", icon: "💼", count: 10 },
  { id: "education", name: "Education", icon: "📚", count: 8 },
  { id: "design", name: "Design", icon: "🎨", count: 7 },
  { id: "vpn", name: "VPN", icon: "🔒", count: 5 },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Netflix Premium",
    slug: "netflix-premium",
    category: "streaming",
    price: 299,
    originalPrice: 599,
    badge: "Best Seller",
    description: "Stream unlimited movies and TV shows in 4K Ultra HD on Netflix. Shared account with guaranteed access and replacement warranty.",
    features: ["4K Ultra HD", "5 screens", "Download enabled", "30-day warranty", "Instant delivery"],
    image: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400&h=300&fit=crop",
    rating: 4.9,
    reviews: 342,
    inStock: true,
    deliveryTime: "Instant",
    plans: [
      { id: "1m", name: "1 Month", price: 299, duration: "30 days", features: ["4K Ultra HD", "5 screens", "Download"] },
      { id: "3m", name: "3 Months", price: 799, duration: "90 days", features: ["4K Ultra HD", "5 screens", "Download", "10% off"] },
      { id: "6m", name: "6 Months", price: 1499, duration: "180 days", features: ["4K Ultra HD", "5 screens", "Download", "20% off"] },
    ],
  },
  {
    id: "2",
    name: "ChatGPT Plus",
    slug: "chatgpt-plus",
    category: "ai-tools",
    price: 799,
    originalPrice: 1200,
    badge: "🔥 Hot",
    description: "Access GPT-4o, DALL-E 3, and advanced features. Fastest AI responses with priority access and image generation.",
    features: ["GPT-4o access", "DALL-E 3", "Priority access", "Plugins & tools", "30-day warranty"],
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&h=300&fit=crop",
    rating: 4.8,
    reviews: 285,
    inStock: true,
    deliveryTime: "10-30 min",
    plans: [
      { id: "1m", name: "1 Month", price: 799, duration: "30 days", features: ["GPT-4o", "DALL-E 3", "Plugins"] },
      { id: "3m", name: "3 Months", price: 2199, duration: "90 days", features: ["GPT-4o", "DALL-E 3", "Plugins", "Save 8%"] },
    ],
  },
  {
    id: "3",
    name: "Spotify Premium",
    slug: "spotify-premium",
    category: "streaming",
    price: 149,
    originalPrice: 299,
    badge: "Popular",
    description: "Ad-free music streaming with unlimited skips, offline downloads, and high-quality audio on Spotify.",
    features: ["Ad-free music", "Offline downloads", "Unlimited skips", "High quality audio", "30-day warranty"],
    image: "https://images.unsplash.com/photo-1611339555312-e607c8352fd7?w=400&h=300&fit=crop",
    rating: 4.7,
    reviews: 198,
    inStock: true,
    deliveryTime: "Instant",
    plans: [
      { id: "1m", name: "1 Month", price: 149, duration: "30 days", features: ["Ad-free", "Offline", "Unlimited skips"] },
      { id: "3m", name: "3 Months", price: 399, duration: "90 days", features: ["Ad-free", "Offline", "Unlimited skips", "Save 10%"] },
      { id: "6m", name: "6 Months", price: 749, duration: "180 days", features: ["Ad-free", "Offline", "Unlimited skips", "Save 15%"] },
    ],
  },
  {
    id: "4",
    name: "Microsoft 365",
    slug: "microsoft-365",
    category: "productivity",
    price: 499,
    originalPrice: 899,
    badge: "Office",
    description: "Full Microsoft Office suite including Word, Excel, PowerPoint, Outlook, Teams and 1TB OneDrive storage.",
    features: ["Word, Excel, PowerPoint", "Outlook & Teams", "1TB OneDrive", "5 devices", "Warranty included"],
    image: "https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=400&h=300&fit=crop",
    rating: 4.8,
    reviews: 156,
    inStock: true,
    deliveryTime: "1-2 hours",
    plans: [
      { id: "1m", name: "1 Month", price: 499, duration: "30 days", features: ["Full Office", "1TB OneDrive", "5 devices"] },
      { id: "12m", name: "1 Year", price: 4999, duration: "365 days", features: ["Full Office", "1TB OneDrive", "5 devices", "Best value"] },
    ],
  },
  {
    id: "5",
    name: "Canva Pro",
    slug: "canva-pro",
    category: "design",
    price: 349,
    originalPrice: 599,
    badge: "Design",
    description: "Unlock premium design tools, 100M+ stock photos, brand kit, background remover and team collaboration on Canva.",
    features: ["100M+ stock assets", "Brand kit", "Background remover", "Magic resize", "Premium templates"],
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=300&fit=crop",
    rating: 4.9,
    reviews: 221,
    inStock: true,
    deliveryTime: "Instant",
    plans: [
      { id: "1m", name: "1 Month", price: 349, duration: "30 days", features: ["All Pro features", "100M+ assets"] },
      { id: "6m", name: "6 Months", price: 1799, duration: "180 days", features: ["All Pro features", "100M+ assets", "Save 14%"] },
    ],
  },
  {
    id: "6",
    name: "Grammarly Premium",
    slug: "grammarly-premium",
    category: "ai-tools",
    price: 249,
    originalPrice: 450,
    badge: "Writer",
    description: "Advanced grammar, plagiarism detection, tone detection, and AI writing suggestions across all platforms.",
    features: ["Advanced grammar", "Plagiarism check", "Tone detection", "AI suggestions", "All platform support"],
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400&h=300&fit=crop",
    rating: 4.7,
    reviews: 189,
    inStock: true,
    deliveryTime: "Instant",
    plans: [
      { id: "1m", name: "1 Month", price: 249, duration: "30 days", features: ["Full premium access"] },
      { id: "3m", name: "3 Months", price: 649, duration: "90 days", features: ["Full premium access", "Save 13%"] },
    ],
  },
  {
    id: "7",
    name: "Amazon Prime Video",
    slug: "amazon-prime-video",
    category: "streaming",
    price: 199,
    originalPrice: 399,
    badge: "",
    description: "Stream thousands of movies and TV shows including Amazon Originals in HD and 4K with no ads.",
    features: ["4K Ultra HD", "Amazon Originals", "No ads", "Download allowed", "Instant access"],
    image: "https://images.unsplash.com/photo-1619857236612-5b8eba4f9c49?w=400&h=300&fit=crop",
    rating: 4.6,
    reviews: 143,
    inStock: true,
    deliveryTime: "Instant",
    plans: [
      { id: "1m", name: "1 Month", price: 199, duration: "30 days", features: ["4K access", "Download", "No ads"] },
      { id: "3m", name: "3 Months", price: 549, duration: "90 days", features: ["4K access", "Download", "No ads", "Save 8%"] },
    ],
  },
  {
    id: "8",
    name: "NordVPN Premium",
    slug: "nordvpn-premium",
    category: "vpn",
    price: 399,
    originalPrice: 699,
    badge: "Security",
    description: "Ultra-fast VPN with 6000+ servers in 60+ countries, zero-log policy, and threat protection.",
    features: ["6000+ servers", "60+ countries", "Zero-log policy", "Threat protection", "6 devices"],
    image: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=400&h=300&fit=crop",
    rating: 4.8,
    reviews: 97,
    inStock: true,
    deliveryTime: "1-3 hours",
    plans: [
      { id: "1m", name: "1 Month", price: 399, duration: "30 days", features: ["All servers", "6 devices", "Threat protection"] },
      { id: "12m", name: "1 Year", price: 3999, duration: "365 days", features: ["All servers", "6 devices", "Threat protection", "Best value"] },
    ],
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "How to Buy Netflix Subscription in Bangladesh Using bKash",
    slug: "buy-netflix-bangladesh-bkash",
    excerpt: "Learn the easiest way to get Netflix Premium in Bangladesh with bKash, Nagad or Rocket payment — step by step guide with instant delivery.",
    content: "",
    image: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=600&h=400&fit=crop",
    category: "Guide",
    author: "Subscriptions BD",
    authorImage: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    date: "2025-03-15",
    readTime: "5 min read",
    tags: ["Netflix", "bKash", "Guide"],
  },
  {
    id: "2",
    title: "ChatGPT Plus vs Claude Pro: Which AI is Better for Bangladeshi Users?",
    slug: "chatgpt-plus-vs-claude-pro-bangladesh",
    excerpt: "A detailed comparison of ChatGPT Plus and Claude Pro for students, freelancers and professionals in Bangladesh — price, features, and use cases.",
    content: "",
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=400&fit=crop",
    category: "Comparison",
    author: "Subscriptions BD",
    authorImage: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    date: "2025-03-10",
    readTime: "8 min read",
    tags: ["ChatGPT", "AI", "Comparison"],
  },
  {
    id: "3",
    title: "Top 10 Digital Subscriptions Every Freelancer in Bangladesh Needs",
    slug: "top-10-subscriptions-freelancers-bangladesh",
    excerpt: "Boost your freelancing career with these must-have digital tools and subscriptions — all available in Bangladesh at affordable BD prices.",
    content: "",
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&h=400&fit=crop",
    category: "List",
    author: "Subscriptions BD",
    authorImage: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    date: "2025-03-05",
    readTime: "10 min read",
    tags: ["Freelancing", "Tools", "Bangladesh"],
  },
  {
    id: "4",
    title: "Canva Pro vs Adobe Express: Best Design Tool for BD Users 2025",
    slug: "canva-pro-vs-adobe-express-bangladesh",
    excerpt: "Which design subscription is worth your money in 2025? We compare Canva Pro and Adobe Express for Bangladeshi designers and marketers.",
    content: "",
    image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&h=400&fit=crop",
    category: "Comparison",
    author: "Subscriptions BD",
    authorImage: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    date: "2025-02-28",
    readTime: "7 min read",
    tags: ["Canva", "Design", "Comparison"],
  },
  {
    id: "5",
    title: "Grammarly Premium Review 2025: Is It Worth It for Bangladeshi Writers?",
    slug: "grammarly-premium-review-bangladesh-2025",
    excerpt: "Full Grammarly Premium review for writers, students and professionals in Bangladesh — features, pricing, and honest verdict.",
    content: "",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&h=400&fit=crop",
    category: "Review",
    author: "Subscriptions BD",
    authorImage: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    date: "2025-02-20",
    readTime: "6 min read",
    tags: ["Grammarly", "Review", "Writing"],
  },
  {
    id: "6",
    title: "Microsoft 365 for Students in Bangladesh: Complete Guide 2025",
    slug: "microsoft-365-students-bangladesh-guide",
    excerpt: "Everything you need to know about Microsoft 365 for students in Bangladesh — how to get it, pricing, features and setup instructions.",
    content: "",
    image: "https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=600&h=400&fit=crop",
    category: "Guide",
    author: "Subscriptions BD",
    authorImage: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&h=100&fit=crop",
    date: "2025-02-15",
    readTime: "9 min read",
    tags: ["Microsoft", "Students", "Guide"],
  },
];

export const siteConfig = {
  name: "Subscriptions BD",
  tagline: "Bangladesh's #1 Digital Subscription Store",
  description: "Premium digital subscriptions at affordable Bangladeshi prices. Pay with bKash, Nagad, Rocket. Instant delivery & warranty guaranteed.",
  whatsapp: "+8801700000000",
  email: "support@subscriptionsbd.net",
  address: "Dhaka, Bangladesh",
  facebook: "https://facebook.com/subscriptionsbd",
  instagram: "https://instagram.com/subscriptionsbd",
  twitter: "https://twitter.com/subscriptionsbd",
  phone: "+880 1700-000000",
};
